### ISSUE TITLE
 Issue starting container

### ISSUE THREAD

**Issue by random0000** [docker-library/logstash#52]
I am using the 2.3 dockerfile and docker-entrypoint.sh.  The container builds without issue when when I try to start it up using: 
docker run -it --rm logstash logstash -e "input { stdin { } } output { stdout { } }"

I get this error on Windows using the new Docker Beta:
standard_init_linux.go:175: exec user process caused "no such file or directory"

I get this error on Centos running the command above:
docker: Error response from daemon: Container command '/docker-entrypoint.sh could not be invoked...

Any help would be appreciated!

**Comment by yosifkit** [comment]
I would guess that the way it opens stdin/stdout does not work on the Docker for Windows Beta.  Not sure why it doesn't work on Centos, I was unable to reproduce it on Debian or Gentoo.  My guess is that the local copy of `docker-entrypoint.sh` needs a `chmod +x docker-entrypoint.sh`.  Next time, I would recommend just git cloning the repo so that the proper permissions are there.

That example config is probably not very useful anyway since it just takes stdin and prints to stdout.  Have you tried to do something more complicated like having it act as a [syslog](http://nathanleclaire.com/blog/2015/04/27/automating-docker-logging-elasticsearch-logstash-kibana-and-logspout/) or [gelf](https://github.com/tianon/docker-elk-stack) endpoint?

**Comment by neddogg** [comment]
@random0000 It seems like you have type logstash twice.
docker run -it --rm logstash logstash -e "input { stdin { } } output { stdout { } }" instead of
docker run -it --rm logstash -e "input { stdin { } } output { stdout { } }"

**Comment by yosifkit** [comment]
@neddogg, you shouldn't need to type it twice; the entrypoint script looks for the command to start with `-` and adds the `logstash` executable for you: https://github.com/docker-library/logstash/blob/e8bb8f5b6dafbfb010797d1f90d4d3b3e36a26f4/docker-entrypoint.sh#L6-L8.
