### ISSUE TITLE
Support for Env-Variable Substitution

### ISSUE THREAD

**Issue by pazoozooCH** [docker-library/logstash#9]
Hi

First of all, thanks for the image.

Consider the following use-case:
- Output to a linked Elasticsearch Docker container

The connection details will be injected by Docker as environment variables. Thus, I would need to be able to substitute Env-Variable placeholders in a config file. Can you propose a solution to this problem or is it a missing feature?

I suppose that this will be a very common (if not THE) use case that people will want to use the image for, so it would be nice if it would be supported by the official image directly.

Thanks Martin

**Comment by md5** [comment]
Looks like there's an open Jira issue for LS to support this directly: https://logstash.jira.com/browse/LOGSTASH-1043

**Comment by md5** [comment]
Although there's also this other one closed as `WONTFIX`: https://logstash.jira.com/browse/LOGSTASH-506

@jordansissel: Sorry to ping you on this, but I couldn't comment on LOGSTASH-1043. Are you still considering support for environment variables in LS config a `WONTFIX` issue?

**Comment by pazoozooCH** [comment]
I've helped myself with a very basic Bash script that will replace all ${NAME} placeholders with the corresponding env variable. I could also add something (a startup flag, a comment in the config file) to opt-in for this feature.

Would you consider accepting a PR with such changes?

**Comment by tianon** [comment]
Since upstream doesn't seem interested in supporting such a feature
("WONTFIX"), I'm definitely wary about adding a workaround to do it
downstream in our image.

**Comment by jordansissel** [comment]
My recommendation when folks ask about variable substitution in logstash config is to have somethinge preprocess their configs (or generate them from templates) before running logstash. The most simple could just be to use m4 or sed to process the config before using it, though I don't have strong recommendations on what you should use here :)

**Comment by jordansissel** [comment]
For context, many config management users generate their logstash config files from some kind of truth source (chef databags/attributes, puppet db/facts, etc). In Docker, environment variables are a kind of truth source, so it makes sense to use that to generate the configuration. I confess I haven't used container linking so I'm not sure how that affects things, but hopefully my encouragement to generate the config on the fly from a template is sufficient an answer. :)

**Comment by pazoozooCH** [comment]
Thanks for the feedback. I have a very simple solution that replaces env variables prior to running the container. I'll clean that up a bit, make it opt-in and file a PR when I find some time...

**Comment by arabold** [comment]
Maybe I'm missing something, so please correct me if wrong. To my understanding it's possible to refer to the linked container by using its name as the hostname. Docker will resolve this automatically for me. So if I'm linking the Logstash container to an Elasticsearch container (named "elasticsearch"), all I need to specify is the docker container name as the target host:

```
output {
  elasticsearch { 
    protocol => "http"
    host => "elasticsearch"
  }
}
```

The same is true for my Kibana image. My configuation looks like this:

```
# The Elasticsearch instance to use for all your queries.
elasticsearch_url: "http://elasticsearch:9200"
```

I'm using Amazon Elastic Beanstalk to setup my environment, but I've learned this trick from a Docker Compose (Fig) setup available here: https://github.com/deviantony/fig-elk

**Comment by tianon** [comment]
I believe that Docker's newer linking features (especially the way Docker networks hijack DNS to provide inter-container resolution via names) make this more of a moot point. :+1:

Personally, I prefer to use `-e` when starting my container to supply my configuration directly inline rather than relying on a file, since it's easier to control and munge that way for my uses.  For example, I've got https://github.com/tianon/docker-elk-stack/blob/a3171a52f7008666723246119a694e26bf4cf26c/docker-compose.yml which starts up a fully-connected ELK stack without anything too complicated IMO. :+1:  (with Logstash in particular configured to accept `gelf` input specifically for use as a Docker `gelf` log driver bucket :metal:)

Regardless, I think the appropriate way to configure Logstash in Docker is to supply said configuration directly, and if generated configuration is necessary, using a simple script to generate it at startup time should be sufficient.  Thanks for the discussion, and sorry for the massive delay in getting back around to this issue!
