### ISSUE TITLE
docker-library-bot not updating 6/Dockerfile?

### ISSUE THREAD

**Issue by ghost** [docker-library/logstash#93]
In [this build](https://doi-janky.infosiftr.net/job/update.sh/job/logstash/1524/), it looks an updated version of Logstash 6 (6.4.3) was found and rendered into the Dockerfile:

```
--- a/6/Dockerfile
+++ b/6/Dockerfile
@@ -1,10 +1,10 @@
-# Logstash 6.4.2
+# Logstash 6.4.3
 
 # This image re-bundles the Docker image from the upstream provider, Elastic.
-FROM docker.elastic.co/logstash/logstash:6.4.2@sha256:75e95100f9830235bc53160b9dd3464a597bd846a3ab716bd55afa348c723065
+FROM docker.elastic.co/logstash/logstash:6.4.3@sha256:392a232fdde65fb4821fc0d5e00ded19fec721226e1550bff4ab8ca84447d719
 
 # The upstream image was built by:
-#   https://github.com/elastic/logstash-docker/tree/6.4.2
+#   https://github.com/elastic/logstash-docker/tree/6.4.3
```

...but it didn't seem to get commited and pushed here.

Is there a tweak needed to get Jenkins to recognise the new version?

Thanks.

**Comment by ghost** [comment]
cc @jethr0null

**Comment by yosifkit** [comment]
cc @tianon It looks like we need to update the jenkins pipeline since it assumes that the version for the commit message is available via an `ENV`.  The same failure will be happening in elasticsearch and kibana.

**Comment by jethr0null** [comment]
If I remember correctly I wound up running update.sh locally and committing the updated Dockerfile before issuing the PRs for Elasticsearch and Kibana.

**Comment by ghost** [comment]
Yes, I did that too. With the release of 6.4.3, we'd expect Jenkins to do that for us, but I think we (@jethr0null and I) broke something that Jenkins needs.

**Comment by yosifkit** [comment]
Jenkins job just has assumptions about the version being in an `ENV` since that is what all our other images have. We just need to adjust the `awk` to work for images that don't have that `ENV` without breaking the regular case: https://github.com/docker-library/oi-janky-groovy/blob/593f90c3450eb343275100a18711ea26a6173782/update.sh/target-pipeline.groovy#L128-L132

**Comment by tianon** [comment]
Fingers crossed, https://doi-janky.infosiftr.net/job/update.sh/job/logstash/1531/console will be the winning build. :+1:

**Edit:**

Looks promising already!

```diff
commit 4fd742915018388ae0f050331760019bad7876f7
Author: Docker Library Bot <github+dockerlibrarybot@infosiftr.com>
Date:   Fri Nov 9 17:54:00 2018 +0000

    Update to 6.4.3

diff --git a/6/Dockerfile b/6/Dockerfile
index 0cfd3dd..456b842 100644
--- a/6/Dockerfile
+++ b/6/Dockerfile
@@ -1,10 +1,10 @@
-# Logstash 6.4.2
+# Logstash 6.4.3
 
 # This image re-bundles the Docker image from the upstream provider, Elastic.
-FROM docker.elastic.co/logstash/logstash:6.4.2@sha256:75e95100f9830235bc53160b9dd3464a597bd846a3ab716bd55afa348c723065
+FROM docker.elastic.co/logstash/logstash:6.4.3@sha256:392a232fdde65fb4821fc0d5e00ded19fec721226e1550bff4ab8ca84447d719
 
 # The upstream image was built by:
-#   https://github.com/elastic/logstash-docker/tree/6.4.2
+#   https://github.com/elastic/logstash-docker/tree/6.4.3
 
 # For a full list of supported images and tags visit https://www.docker.elastic.co
 
```

**Comment by ghost** [comment]
I'm going to reveal the full depth of my ignorance here, but where would I find the process that would push this image to the Hub? It looks like the build was successful but my hopes of pulling it from the Hub were dashed. :)

```
λ  docker pull logstash:6.4.3
Error response from daemon: manifest for logstash:6.4.3 not found
```

**Comment by tianon** [comment]
Nope, it's waiting for a PR to https://github.com/docker-library/official-images.

I was looking to do one today, but https://doi-janky.infosiftr.net/job/update.sh/job/elasticsearch/ is failing so I can't get all of ELK updated to 6.4.3 yet -- it looks like it's failing the test because now the image always runs the bootstrap checks and those fail.  I looked for a bit to try and get it to not run the bootstrap checks in https://github.com/docker-library/official-images/blob/d6d57d37e28d3f32dd268618f8fcf8f727ee282b/test/tests/elasticsearch-basics/run.sh#L16, but wasn't successful.  Is there any way we can get the image to run in development mode and still be able to connect to it from another container for that test?

**Comment by ghost** [comment]
Thanks, @tianon. It's all coming together!

docker-library/official-images#5064 sorts out the tests. 👍

**Comment by tianon** [comment]
Fingers crossed for https://doi-janky.infosiftr.net/job/update.sh/job/elasticsearch/1549/console so I (or you!) can open a PR to https://github.com/docker-library/official-images. :+1:
